.gitignore
=> fix: ignore .gitkeep in .gitignore #5

src/main/java/karmosin/ResultEmailer.java
=> feat: ResultEmailer interface #7

.gitignore
=> fix: ignore bin folder #9

build.gradle
=> fix: Modifies build.gradle to specify the JDK version to be 11

src/main/java/karmosin/WebHookHandler.java
=> fix wrong HttpRequest/HttpResponse import in WebHookHandler

build.gradle, src/main/java/karmosin/WebHookHandler.java
=> fix: move to jetty for webhook handling

src/main/java/karmosin/ContinuousIntegrationJobRunner.java
=> feat: add runCheck to ContinuousIntegrationJobRunner

src/main/java/karmosin/WebHookHandler.java
=> fix: typo parseEventhandle -> parseEvent in karmosin.WebHookHandler

build.gradle
=> fix: use jetty version 10 as 11 use jakarta

build.gradle
=> fix gradle java test

README.md
=> doc: readme draft

README.md
=> doc: adds body to 'Team' section in readme

README.md
=> doc: fixes the format issue of README

src/main/java/crimson/ContinuousIntegrationHandler.java, src/main/java/crimson/WebHookHandler.java, src/main/java/karmosin/ContinuousIntegrationJob.java
=> add job ID for each CI Job

src/main/java/crimson/ContinuousIntegrationHandler.java, src/main/java/crimson/WebHookHandler.java
=> fix: don't create ContinuousIntegrationJob if push event = delete branch

src/main/java/karmosin/ContinuousIntegrationJobRunner.java
=> doc for continuous integration job runner interface

README.md
=> doc: Adds "Functionality" to README

README.md
=> doc: Adds Tobias' contributions to README

src/main/java/crimson/ContinuousIntegrationHandler.java
=> feat: call handler.responseEvent when job is done

src/main/java/crimson/Server.java
=> feat: server log request

src/main/java/crimson/CommitStatusHandler.java
=> feat: print GitHub api resp

README.md
=> doc: adds Siyao's contribution

src/main/java/crimson/WebHookHandler.java, src/test/java/WebHookHandlerTests.java
=> fix: WebHookHandler not getting the correct commit hash

src/main/java/crimson/ContinuousIntegrationHandler.java, src/main/java/crimson/Server.java, src/main/java/crimson/WebHookHandler.java
=> feat: preserve build history

README.md
=> doc: add how to use

README.md
=> doc: Add Filips contribution to readme.

README.md
=> doc: how to test

src/main/java/crimson/ContinuousIntegrationHandler.java
=> feat: remove temp directory after job

src/main/java/crimson/ContinuousIntegrationHandler.java
=> feat: show commit has in jobName/commit file
